name: Amanda McAlister
favicon: null
layout_spectrum: 0.057084681233391166
typography_spectrum: 0.10698966355994344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0eaff'
    - '#19191b'
    - '#765955'
    - '#a58a75'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.5495635538827628
purpose: []
